### PR TITLE
Revert dual blending blacklist on Intel.

### PR DESCRIPTION
**Pull request by pal1000**
It was fixed in latest driver: 15.33.32.4061 (10.18.10.4061).

### CODE REVIEW

**Comment by hrydgard** [comment]
Hm. Maybe we can add a check for the driver version? It should be in RENDERER or something. It would be bad if we broke on all older drivers, as people are pretty bad at updating their GPU drivers in general...

**Comment by pal1000** [comment]
Well, for this particular case, this is all know:
-4th  generation Intel Core; I don't know anything about this. Never had hardware with this specs.
-3rd generation Intel Core with 10.18.10.3958 and older are affected;
-2nd generation Intel Core with 9.17.10.3517 or 9.17.10.3347 are unaffected. Older came before PPSSPP used dual blending and before I even had hardware with these specs;
-1st generation Intel Core does not qualify for dual blending (OpenGL 2.1 cap).

**Comment by unknownbrackets** [comment]
Is 9.17 the latest driver for 2nd gen?  Maybe we only blacklist 10.* with < that version?

Does the developer tools -> system information show the renderer properly?

-[Unknown]

**Comment by pal1000** [comment]
The latest drivers are as follows:
2nd generation: 9.17.10.4101
3rd and 4th generation common: 10.18.10.4061;
4th gen exclusive (OpenGL 4.3): 10.18.10.4080.

2nd generation was not affected, at least not in the last year and half.
3rd generation is affected with drivers 10.18.10.3958 and older.
Don't know anything about 4th generation as I don't have hardware to test on.

I think it's pretty accurate if you blacklist 10.18.10.x with x<4061.

System Information:
 
menu_00000
menu_00001

It appears that PPSSPP detects OpenGL support as being capped at 3.3.0 but according 
to these it should be 4.0.0:
https://gist.github.com/pal1000/c9f12f04544d7ba1ce27
http://downloadmirror.intel.com/24593/eng/ReleaseNotes_GFX_15.33.32.64.4061.pdf

**Comment by unknownbrackets** [comment]
According to this:
http://www.intel.com/support/graphics/sb/CS-020667.htm

We can potentially just look at the last number (the build number.)  But I'm confused since the latest ones seem to be 15.* now...

-[Unknown]

**Comment by pal1000** [comment]
Intel drivers have 2 versions. One is the installer version and the other is driver files version. Applications that check for driver version only have access to driver files version e.g. the one listed in device manager. The good news is the build number is common for both versioning systems.
The challenging part is that you'll need code to determine CPU generation. Then you compare driver build numbers for a given CPU generation.

**Comment by hrydgard** [comment]
native is no longer an active project, it was merged into PPSSPP. Closing issue.

**Pull request closed without merging**
